In [2]:
import numpy as np

a=[1,2,3,4]
b=np.array(a)
print(b)
print(type(b))

[1 2 3 4]
<class 'numpy.ndarray'>


In [6]:
a=[1,2,3,4,'5',4.5]
b=np.array(a,dtype=str)
print(b)

['1' '2' '3' '4' '5' '4.5']


In [8]:
a=[1,2,3,4,'5',4.5]
b=np.array(a*3)
print(b)

['1' '2' '3' '4' '5' '4.5' '1' '2' '3' '4' '5' '4.5' '1' '2' '3' '4' '5'
 '4.5']


In [14]:
c=np.ones(3,dtype=int)
print(c)


[1 1 1]


In [18]:
d=np.zeros((3,4),dtype=int)
d


array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [21]:
e=np.full(3,5 ,dtype=float)
e

array([5., 5., 5.])

In [24]:
f=np.arange(10)
f

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
g=np.arange(2,20,2)
g

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [30]:
h=np.linspace(2,10)
h
print(h[1]-h[0])
print(h[2]-h[1])

0.16326530612244916
0.16326530612244872


In [34]:
i=np.linspace(2,10,5,dtype=int,endpoint=False)
i

array([2, 3, 5, 6, 8])

In [36]:
j=np.identity(3)
j

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
k=np.eye(3,5)
k

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [50]:
l=np.random.rand(3)
l

array([0.90986134, 0.76566598, 0.19940265])

In [53]:
m=np.random.rand(2,3)
m

array([[0.05564366, 0.07461711, 0.14944752],
       [0.38728256, 0.79485982, 0.30435849]])

In [57]:
n=np.random.rand(10)*10
n

array([3.38283645, 4.21608283, 3.2986877 , 4.12424342, 5.29266751,
       6.36307144, 8.61704085, 4.84252529, 7.04189963, 8.89929622])

In [58]:
# Indexing and Slicing

In [60]:
li=[1,2,3,4,5]
arr=np.array(li)
print(arr)

[1 2 3 4 5]


In [73]:
print(arr.data)
print(arr.shape)
print(arr.dtype)
print(arr.strides)

(5,)
int32
(4,)


In [75]:
print(arr[3])
print(arr[1:4])

4
[2 3 4]


In [65]:
li_2d=[[1,1,1,1],[2,2,2,2],[3,3,3,3]]
arr_2d=np.array(li_2d)
print(arr_2d)

[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]]


In [67]:
print(arr_2d.data)

In [69]:
print(arr_2d.shape)

(3, 4)


In [71]:
print(arr_2d.dtype)

int32


In [77]:
print(arr_2d.strides)

(16, 4)


In [80]:
print(arr_2d[1][1])
print(arr_2d[2,1])

2
3


In [83]:
#Slicing in 2_d array
print(li_2d[1][:3])
print(arr_2d[1][:3])

[2, 2, 2]
[2 2 2]


In [85]:
print(li_2d[:3][2])

[3, 3, 3, 3]


In [88]:
x=li_2d[0:3]
print(x)
y=x[2]
print(y)

[[1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3]]
[3, 3, 3, 3]


In [96]:
print(arr_2d[0:3, 1])

[1 2 3]


In [98]:
print(arr_2d[0:3,1:3])

[[1 1]
 [2 2]
 [3 3]]


In [103]:
#Mathematical Operations
import numpy as np
li=[1,2,3,4,5]
a=np.random.randint(1,20,5)
b=np.random.randint(1,20,5)
print(li)
print(a)
print(b)

[1, 2, 3, 4, 5]
[16  7 10 15 17]
[11 15 15 10  1]


In [105]:
li=[i+1 for i in li]
li

[3, 4, 5, 6, 7]

In [106]:
a=a+1
a


array([17,  8, 11, 16, 18])

In [109]:
c=a+b
c

array([28, 23, 26, 26, 19])

In [111]:
c=a*b
c

array([187, 120, 165, 160,  18])

In [113]:
g=a//b
g

array([ 1,  0,  0,  1, 18])

In [117]:
h=a**b
h

array([-1942714447,           0,  1632031715,           0,          18])

In [122]:
print(a)
print(a.sum())
print(a.mean())
print(a.min())
print(a.argmin())
print(a.argmax())

[17  8 11 16 18]
70
14.0
8
1
4


In [125]:
print(a)
print(b)

[17  8 11 16 18]
[11 15 15 10  1]


In [127]:
a>b

array([ True, False, False,  True,  True])

In [129]:
a<b

array([False,  True,  True, False, False])

In [131]:
a==b

array([False, False, False, False, False])

In [133]:
print(np.logical_or(a,b))

[ True  True  True  True  True]


In [135]:
print(np.logical_and(a,b))

[ True  True  True  True  True]


In [137]:
print(np.logical_xor(a,b))

[False False False False False]


In [139]:
print(np.logical_not(a))

[False False False False False]


In [141]:
print(arr_2d)

[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]]


In [148]:
print(np.logical_xor(arr_2d[1][1],arr_2d[1][2]))
print(np.logical_xor(arr_2d[:2,1],arr_2d[:2,2]))
print(np.logical_xor(arr_2d[1,:4],arr_2d[2,:4]))

False
[False False]
[False False False False]


In [158]:
#BOOLean Indexing
z=np.random.randint(1,20,8)
print(z)
print(z>10)

#Accessing elements greater than 10
bool_arr= z>10
print(bool_arr)
new_arr=z[bool_arr]
print(new_arr)


[12  3  4  8 18 11 14 19]
[ True False False False  True  True  True  True]
[ True False False False  True  True  True  True]
[12 18 11 14 19]


In [161]:
new_arr=z[z>10]
print(new_arr)

[12 18 11 14 19]


In [166]:
new_arr=z[(z>10)& (z<15)]
print(new_arr)

[12 11 14]


In [169]:
print(a)
c=a
c

[17  8 11 16 18]


array([17,  8, 11, 16, 18])

In [172]:
c[:3]=19
print(c)
c[c>17]=100
print(c)

[19 19 19 16 18]
[100 100 100  16 100]


In [175]:
print(c[c==100])
ind=np.where(c==100)
ind

[100 100 100 100]


(array([0, 1, 2, 4], dtype=int64),)

In [181]:
print(a)
print(b)
print(b[ind])

[100 100 100  16 100]
[11 15 15 10  1]
[11 15 15  1]


In [189]:
a=np.random.randint(1,40,(5,6))
a

array([[29, 22, 38,  8, 35, 27],
       [20,  5,  8, 18,  3, 31],
       [16, 16, 11,  2, 17, 23],
       [19,  9, 22, 25, 10, 36],
       [34, 28,  1,  2, 16, 21]])

In [190]:
bool_arr=a>20
print(bool_arr)

[[ True  True  True False  True  True]
 [False False False False False  True]
 [False False False False False  True]
 [False False  True  True False  True]
 [ True  True False False False  True]]


In [196]:
ans=a[bool_arr]
print(ans)

[29 22 38 35 27 31 23 22 25 36 34 28 21]


In [198]:
c=a
print(c)


[[29 22 38  8 35 27]
 [20  5  8 18  3 31]
 [16 16 11  2 17 23]
 [19  9 22 25 10 36]
 [34 28  1  2 16 21]]


In [201]:
c[bool_arr]=100
print(c)

[[100 100 100   8 100 100]
 [ 20   5   8  18   3 100]
 [ 16  16  11   2  17 100]
 [ 19   9 100 100  10 100]
 [100 100   1   2  16 100]]


In [203]:
d=np.random.randint(1,10,(2,2))
print(d)

[[7 4]
 [6 1]]


In [208]:
d_bool=np.array([[True,False],[False,True],[True,True]])
print(d_bool)

[[ True False]
 [False  True]
 [ True  True]]


In [212]:
# print(d[d_bool])

In [215]:
print(c)

[[100 100 100   8 100 100]
 [ 20   5   8  18   3 100]
 [ 16  16  11   2  17 100]
 [ 19   9 100 100  10 100]
 [100 100   1   2  16 100]]


In [217]:
bool_arr=c[:,3]==100
print(bool_arr)

[False False False  True False]


In [219]:
c[bool_arr,3]=99
print(c)

[[100 100 100   8 100 100]
 [ 20   5   8  18   3 100]
 [ 16  16  11   2  17 100]
 [ 19   9 100  99  10 100]
 [100 100   1   2  16 100]]


In [220]:
#NumPy Broadcasting
# If two array are not of size how it will be treated - This allcases comes in broadcasting
#If dimesions are equal then it is compatible
#Also if array;s dimension ,one of them is 1

In [224]:
x=np.random.randint(1,10,(3,3))
print(x)
y=np.random.randint(1,10,(3,3))
print(y)
print(x+y)

[[7 7 5]
 [6 9 4]
 [7 6 9]]
[[6 1 7]
 [6 5 4]
 [1 4 2]]
[[13  8 12]
 [12 14  8]
 [ 8 10 11]]


In [233]:
a=np.random.randint(1,10,(3,3))
print(a)
b=np.random.randint(1,10,(3))
print(b)
ans=a-b
print(ans)

[[3 8 8]
 [5 5 6]
 [7 7 6]]
[8 5 4]
[[-5  3  4]
 [-3  0  2]
 [-1  2  2]]
