In [20]:
import numpy as np

In [21]:
X = np.array([[0,0], [0,1], [1,0], [1,1]])
Y = np.array([[0,0,0,1]]).T
X.shape, Y.shape

((4, 2), (4, 1))

In [22]:
def sig(z):
    return 1/(1 + np.exp(-z))

In [23]:
def derivativeSig(x):
    return sig(z)*(1 - sig(z))

In [24]:
# no hidden layer weights
weights = 2* np.random.random((2, 1)) - 1
bias = 2 * np.random.random(1) - 1
weights, bias

(array([[-0.49552179],
        [-0.50370837]]),
 array([-0.66450346]))

In [25]:
# forward propagation without any hidden layer
output0 = X
output = sig(np.dot(output0, weights) + bias)
output

array([[0.3397287 ],
       [0.23717836],
       [0.2386627 ],
       [0.15926144]])

In [26]:
# one hidden layer weights
wh = 2* np.random.random((2, 2)) - 1   # 2,2 is size of hidden weight size
bh = 2* np.random.random((1, 2)) - 1
wo = 2 * np.random.random((2, 1)) - 1
bo = 2 * np.random.random((1,1)) - 1

In [27]:
# forward propagation with one hidden layer
output0 = X
outputHidden = sig(np.dot(output0, wh) + bh)
output = sig(np.dot(outputHidden, wo) + bo)
output

array([[0.53777434],
       [0.55301807],
       [0.51418568],
       [0.52881976]])